# This is a config for E2B sandbox template.
# You can use template ID (bihc2lzasz44j60596e1) or template name (lovable-kaif-1try) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-kaif-1try") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-kaif-1try") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-kaif-1try')

team_id = "837ef820-6b1a-431a-93f6-ddff4a8ec318"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-kaif-1try"
template_id = "bihc2lzasz44j60596e1"
